//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.ProxyCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteBE", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class ClienteBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnuladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdTipoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PagadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReservadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestWeb.ProxyCliente.UbigeoBE UbigeoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Anulado {
            get {
                return this.AnuladoField;
            }
            set {
                if ((this.AnuladoField.Equals(value) != true)) {
                    this.AnuladoField = value;
                    this.RaisePropertyChanged("Anulado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdTipoCliente {
            get {
                return this.IdTipoClienteField;
            }
            set {
                if ((this.IdTipoClienteField.Equals(value) != true)) {
                    this.IdTipoClienteField = value;
                    this.RaisePropertyChanged("IdTipoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo {
            get {
                return this.IdUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUbigeoField, value) != true)) {
                    this.IdUbigeoField = value;
                    this.RaisePropertyChanged("IdUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Pagado {
            get {
                return this.PagadoField;
            }
            set {
                if ((this.PagadoField.Equals(value) != true)) {
                    this.PagadoField = value;
                    this.RaisePropertyChanged("Pagado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Reservado {
            get {
                return this.ReservadoField;
            }
            set {
                if ((this.ReservadoField.Equals(value) != true)) {
                    this.ReservadoField = value;
                    this.RaisePropertyChanged("Reservado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoCasa {
            get {
                return this.TelefonoCasaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoCasaField, value) != true)) {
                    this.TelefonoCasaField = value;
                    this.RaisePropertyChanged("TelefonoCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoCelular {
            get {
                return this.TelefonoCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoCelularField, value) != true)) {
                    this.TelefonoCelularField = value;
                    this.RaisePropertyChanged("TelefonoCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestWeb.ProxyCliente.UbigeoBE Ubigeo {
            get {
                return this.UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.UbigeoField, value) != true)) {
                    this.UbigeoField = value;
                    this.RaisePropertyChanged("Ubigeo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbigeoBE", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class UbigeoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContinenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idContinenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUbigeoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Continente {
            get {
                return this.ContinenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinenteField, value) != true)) {
                    this.ContinenteField = value;
                    this.RaisePropertyChanged("Continente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.idCiudadField, value) != true)) {
                    this.idCiudadField = value;
                    this.RaisePropertyChanged("idCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idContinente {
            get {
                return this.idContinenteField;
            }
            set {
                if ((object.ReferenceEquals(this.idContinenteField, value) != true)) {
                    this.idContinenteField = value;
                    this.RaisePropertyChanged("idContinente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idDepartamento {
            get {
                return this.idDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.idDepartamentoField, value) != true)) {
                    this.idDepartamentoField = value;
                    this.RaisePropertyChanged("idDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.idDistritoField, value) != true)) {
                    this.idDistritoField = value;
                    this.RaisePropertyChanged("idDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idPais {
            get {
                return this.idPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idPaisField, value) != true)) {
                    this.idPaisField = value;
                    this.RaisePropertyChanged("idPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.idProvinciaField, value) != true)) {
                    this.idProvinciaField = value;
                    this.RaisePropertyChanged("idProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUbigeo {
            get {
                return this.idUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.idUbigeoField, value) != true)) {
                    this.idUbigeoField = value;
                    this.RaisePropertyChanged("idUbigeo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/DevuelveClientePorDNI", ReplyAction="http://tempuri.org/IServicioCliente/DevuelveClientePorDNIResponse")]
        TestWeb.ProxyCliente.ClienteBE DevuelveClientePorDNI(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/DevuelveClientePorDNI", ReplyAction="http://tempuri.org/IServicioCliente/DevuelveClientePorDNIResponse")]
        System.Threading.Tasks.Task<TestWeb.ProxyCliente.ClienteBE> DevuelveClientePorDNIAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        bool InsertarCliente(TestWeb.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarClienteAsync(TestWeb.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(TestWeb.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(TestWeb.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/FrecuenciaClientes", ReplyAction="http://tempuri.org/IServicioCliente/FrecuenciaClientesResponse")]
        TestWeb.ProxyCliente.ClienteBE[] FrecuenciaClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/FrecuenciaClientes", ReplyAction="http://tempuri.org/IServicioCliente/FrecuenciaClientesResponse")]
        System.Threading.Tasks.Task<TestWeb.ProxyCliente.ClienteBE[]> FrecuenciaClientesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioClienteChannel : TestWeb.ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<TestWeb.ProxyCliente.IServicioCliente>, TestWeb.ProxyCliente.IServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWeb.ProxyCliente.ClienteBE DevuelveClientePorDNI(string dni) {
            return base.Channel.DevuelveClientePorDNI(dni);
        }
        
        public System.Threading.Tasks.Task<TestWeb.ProxyCliente.ClienteBE> DevuelveClientePorDNIAsync(string dni) {
            return base.Channel.DevuelveClientePorDNIAsync(dni);
        }
        
        public bool InsertarCliente(TestWeb.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.InsertarCliente(objClienteBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClienteAsync(TestWeb.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.InsertarClienteAsync(objClienteBE);
        }
        
        public bool ActualizarCliente(TestWeb.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.ActualizarCliente(objClienteBE);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(TestWeb.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.ActualizarClienteAsync(objClienteBE);
        }
        
        public TestWeb.ProxyCliente.ClienteBE[] FrecuenciaClientes() {
            return base.Channel.FrecuenciaClientes();
        }
        
        public System.Threading.Tasks.Task<TestWeb.ProxyCliente.ClienteBE[]> FrecuenciaClientesAsync() {
            return base.Channel.FrecuenciaClientesAsync();
        }
    }
}
