//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoServicios.ProxyHabitacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HabitacionBE", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class HabitacionBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FechaEspecialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdHabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionEstado {
            get {
                return this.DescripcionEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionEstadoField, value) != true)) {
                    this.DescripcionEstadoField = value;
                    this.RaisePropertyChanged("DescripcionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTipo {
            get {
                return this.DescripcionTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionTipoField, value) != true)) {
                    this.DescripcionTipoField = value;
                    this.RaisePropertyChanged("DescripcionTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FechaEspecial {
            get {
                return this.FechaEspecialField;
            }
            set {
                if ((this.FechaEspecialField.Equals(value) != true)) {
                    this.FechaEspecialField = value;
                    this.RaisePropertyChanged("FechaEspecial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdHabitacion {
            get {
                return this.IdHabitacionField;
            }
            set {
                if ((this.IdHabitacionField.Equals(value) != true)) {
                    this.IdHabitacionField = value;
                    this.RaisePropertyChanged("IdHabitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSede {
            get {
                return this.IdSedeField;
            }
            set {
                if ((this.IdSedeField.Equals(value) != true)) {
                    this.IdSedeField = value;
                    this.RaisePropertyChanged("IdSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdTipo {
            get {
                return this.IdTipoField;
            }
            set {
                if ((this.IdTipoField.Equals(value) != true)) {
                    this.IdTipoField = value;
                    this.RaisePropertyChanged("IdTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Piso {
            get {
                return this.PisoField;
            }
            set {
                if ((this.PisoField.Equals(value) != true)) {
                    this.PisoField = value;
                    this.RaisePropertyChanged("Piso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SedeBE", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class SedeBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte idSedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUbigeoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte idSede {
            get {
                return this.idSedeField;
            }
            set {
                if ((this.idSedeField.Equals(value) != true)) {
                    this.idSedeField = value;
                    this.RaisePropertyChanged("idSede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUbigeo {
            get {
                return this.idUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.idUbigeoField, value) != true)) {
                    this.idUbigeoField = value;
                    this.RaisePropertyChanged("idUbigeo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyHabitacion.IServicioHabitacion")]
    public interface IServicioHabitacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/ListarHabitacionPorFecha", ReplyAction="http://tempuri.org/IServicioHabitacion/ListarHabitacionPorFechaResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE> ListarHabitacionPorFecha(byte IdSede, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/ListarHabitacionPorFecha", ReplyAction="http://tempuri.org/IServicioHabitacion/ListarHabitacionPorFechaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE>> ListarHabitacionPorFechaAsync(byte IdSede, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/ListarHabitacionesLibres", ReplyAction="http://tempuri.org/IServicioHabitacion/ListarHabitacionesLibresResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE> ListarHabitacionesLibres(byte IdSede, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/ListarHabitacionesLibres", ReplyAction="http://tempuri.org/IServicioHabitacion/ListarHabitacionesLibresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE>> ListarHabitacionesLibresAsync(byte IdSede, System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/ListarPrecioHabitacionesPorSede", ReplyAction="http://tempuri.org/IServicioHabitacion/ListarPrecioHabitacionesPorSedeResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE> ListarPrecioHabitacionesPorSede(byte IdSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/ListarPrecioHabitacionesPorSede", ReplyAction="http://tempuri.org/IServicioHabitacion/ListarPrecioHabitacionesPorSedeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE>> ListarPrecioHabitacionesPorSedeAsync(byte IdSede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/DevuelveHabitacion", ReplyAction="http://tempuri.org/IServicioHabitacion/DevuelveHabitacionResponse")]
        CapaAccesoServicios.ProxyHabitacion.HabitacionBE DevuelveHabitacion(int idHabitacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/DevuelveHabitacion", ReplyAction="http://tempuri.org/IServicioHabitacion/DevuelveHabitacionResponse")]
        System.Threading.Tasks.Task<CapaAccesoServicios.ProxyHabitacion.HabitacionBE> DevuelveHabitacionAsync(int idHabitacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/ListarSede", ReplyAction="http://tempuri.org/IServicioHabitacion/ListarSedeResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.SedeBE> ListarSede();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHabitacion/ListarSede", ReplyAction="http://tempuri.org/IServicioHabitacion/ListarSedeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.SedeBE>> ListarSedeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioHabitacionChannel : CapaAccesoServicios.ProxyHabitacion.IServicioHabitacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioHabitacionClient : System.ServiceModel.ClientBase<CapaAccesoServicios.ProxyHabitacion.IServicioHabitacion>, CapaAccesoServicios.ProxyHabitacion.IServicioHabitacion {
        
        public ServicioHabitacionClient() {
        }
        
        public ServicioHabitacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioHabitacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHabitacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHabitacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE> ListarHabitacionPorFecha(byte IdSede, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ListarHabitacionPorFecha(IdSede, FechaInicio, FechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE>> ListarHabitacionPorFechaAsync(byte IdSede, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ListarHabitacionPorFechaAsync(IdSede, FechaInicio, FechaFin);
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE> ListarHabitacionesLibres(byte IdSede, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ListarHabitacionesLibres(IdSede, FechaInicio, FechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE>> ListarHabitacionesLibresAsync(byte IdSede, System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.ListarHabitacionesLibresAsync(IdSede, FechaInicio, FechaFin);
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE> ListarPrecioHabitacionesPorSede(byte IdSede) {
            return base.Channel.ListarPrecioHabitacionesPorSede(IdSede);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.HabitacionBE>> ListarPrecioHabitacionesPorSedeAsync(byte IdSede) {
            return base.Channel.ListarPrecioHabitacionesPorSedeAsync(IdSede);
        }
        
        public CapaAccesoServicios.ProxyHabitacion.HabitacionBE DevuelveHabitacion(int idHabitacion) {
            return base.Channel.DevuelveHabitacion(idHabitacion);
        }
        
        public System.Threading.Tasks.Task<CapaAccesoServicios.ProxyHabitacion.HabitacionBE> DevuelveHabitacionAsync(int idHabitacion) {
            return base.Channel.DevuelveHabitacionAsync(idHabitacion);
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.SedeBE> ListarSede() {
            return base.Channel.ListarSede();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyHabitacion.SedeBE>> ListarSedeAsync() {
            return base.Channel.ListarSedeAsync();
        }
    }
}
