//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoServicios.ProxyReserva {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaBE", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class ReservaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdEstadoReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdHabitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdReservaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFinReserva {
            get {
                return this.FechaFinReservaField;
            }
            set {
                if ((this.FechaFinReservaField.Equals(value) != true)) {
                    this.FechaFinReservaField = value;
                    this.RaisePropertyChanged("FechaFinReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicioReserva {
            get {
                return this.FechaInicioReservaField;
            }
            set {
                if ((this.FechaInicioReservaField.Equals(value) != true)) {
                    this.FechaInicioReservaField = value;
                    this.RaisePropertyChanged("FechaInicioReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaSalida {
            get {
                return this.FechaSalidaField;
            }
            set {
                if ((this.FechaSalidaField.Equals(value) != true)) {
                    this.FechaSalidaField = value;
                    this.RaisePropertyChanged("FechaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdEstadoReserva {
            get {
                return this.IdEstadoReservaField;
            }
            set {
                if ((this.IdEstadoReservaField.Equals(value) != true)) {
                    this.IdEstadoReservaField = value;
                    this.RaisePropertyChanged("IdEstadoReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdHabitacion {
            get {
                return this.IdHabitacionField;
            }
            set {
                if ((this.IdHabitacionField.Equals(value) != true)) {
                    this.IdHabitacionField = value;
                    this.RaisePropertyChanged("IdHabitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdReserva {
            get {
                return this.IdReservaField;
            }
            set {
                if ((this.IdReservaField.Equals(value) != true)) {
                    this.IdReservaField = value;
                    this.RaisePropertyChanged("IdReserva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyReserva.IServicioReserva")]
    public interface IServicioReserva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/InsertarReserva", ReplyAction="http://tempuri.org/IServicioReserva/InsertarReservaResponse")]
        bool InsertarReserva(CapaAccesoServicios.ProxyReserva.ReservaBE objReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/InsertarReserva", ReplyAction="http://tempuri.org/IServicioReserva/InsertarReservaResponse")]
        System.Threading.Tasks.Task<bool> InsertarReservaAsync(CapaAccesoServicios.ProxyReserva.ReservaBE objReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ActualizarReserva", ReplyAction="http://tempuri.org/IServicioReserva/ActualizarReservaResponse")]
        bool ActualizarReserva(CapaAccesoServicios.ProxyReserva.ReservaBE objReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ActualizarReserva", ReplyAction="http://tempuri.org/IServicioReserva/ActualizarReservaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarReservaAsync(CapaAccesoServicios.ProxyReserva.ReservaBE objReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/DevuelveReservasCliente", ReplyAction="http://tempuri.org/IServicioReserva/DevuelveReservasClienteResponse")]
        CapaAccesoServicios.ProxyReserva.ReservaBE[] DevuelveReservasCliente(byte IdCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/DevuelveReservasCliente", ReplyAction="http://tempuri.org/IServicioReserva/DevuelveReservasClienteResponse")]
        System.Threading.Tasks.Task<CapaAccesoServicios.ProxyReserva.ReservaBE[]> DevuelveReservasClienteAsync(byte IdCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioReservaChannel : CapaAccesoServicios.ProxyReserva.IServicioReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReservaClient : System.ServiceModel.ClientBase<CapaAccesoServicios.ProxyReserva.IServicioReserva>, CapaAccesoServicios.ProxyReserva.IServicioReserva {
        
        public ServicioReservaClient() {
        }
        
        public ServicioReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarReserva(CapaAccesoServicios.ProxyReserva.ReservaBE objReserva) {
            return base.Channel.InsertarReserva(objReserva);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarReservaAsync(CapaAccesoServicios.ProxyReserva.ReservaBE objReserva) {
            return base.Channel.InsertarReservaAsync(objReserva);
        }
        
        public bool ActualizarReserva(CapaAccesoServicios.ProxyReserva.ReservaBE objReserva) {
            return base.Channel.ActualizarReserva(objReserva);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarReservaAsync(CapaAccesoServicios.ProxyReserva.ReservaBE objReserva) {
            return base.Channel.ActualizarReservaAsync(objReserva);
        }
        
        public CapaAccesoServicios.ProxyReserva.ReservaBE[] DevuelveReservasCliente(byte IdCliente) {
            return base.Channel.DevuelveReservasCliente(IdCliente);
        }
        
        public System.Threading.Tasks.Task<CapaAccesoServicios.ProxyReserva.ReservaBE[]> DevuelveReservasClienteAsync(byte IdCliente) {
            return base.Channel.DevuelveReservasClienteAsync(IdCliente);
        }
    }
}
