//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoServicios.ProxyUbigeo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbigeoBE", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class UbigeoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContinenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idContinenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUbigeoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Continente {
            get {
                return this.ContinenteField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinenteField, value) != true)) {
                    this.ContinenteField = value;
                    this.RaisePropertyChanged("Continente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idCiudad {
            get {
                return this.idCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.idCiudadField, value) != true)) {
                    this.idCiudadField = value;
                    this.RaisePropertyChanged("idCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idContinente {
            get {
                return this.idContinenteField;
            }
            set {
                if ((object.ReferenceEquals(this.idContinenteField, value) != true)) {
                    this.idContinenteField = value;
                    this.RaisePropertyChanged("idContinente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idDepartamento {
            get {
                return this.idDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.idDepartamentoField, value) != true)) {
                    this.idDepartamentoField = value;
                    this.RaisePropertyChanged("idDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idDistrito {
            get {
                return this.idDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.idDistritoField, value) != true)) {
                    this.idDistritoField = value;
                    this.RaisePropertyChanged("idDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idPais {
            get {
                return this.idPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idPaisField, value) != true)) {
                    this.idPaisField = value;
                    this.RaisePropertyChanged("idPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.idProvinciaField, value) != true)) {
                    this.idProvinciaField = value;
                    this.RaisePropertyChanged("idProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUbigeo {
            get {
                return this.idUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.idUbigeoField, value) != true)) {
                    this.idUbigeoField = value;
                    this.RaisePropertyChanged("idUbigeo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUbigeo.IServicioUbigeo")]
    public interface IServicioUbigeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarDepartamentosResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE> ListarDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarDepartamentosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE>> ListarDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarProvinciasDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarProvinciasDepartamentoResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE> ListarProvinciasDepartamento(string idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarProvinciasDepartamento", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarProvinciasDepartamentoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE>> ListarProvinciasDepartamentoAsync(string idDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarDistritosProvincia", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarDistritosProvinciaResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE> ListarDistritosProvincia(string idDepartamento, string idProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ListarDistritosProvincia", ReplyAction="http://tempuri.org/IServicioUbigeo/ListarDistritosProvinciaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE>> ListarDistritosProvinciaAsync(string idDepartamento, string idProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/DevuelveUbigeo", ReplyAction="http://tempuri.org/IServicioUbigeo/DevuelveUbigeoResponse")]
        CapaAccesoServicios.ProxyUbigeo.UbigeoBE DevuelveUbigeo(string idUbigeo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/DevuelveUbigeo", ReplyAction="http://tempuri.org/IServicioUbigeo/DevuelveUbigeoResponse")]
        System.Threading.Tasks.Task<CapaAccesoServicios.ProxyUbigeo.UbigeoBE> DevuelveUbigeoAsync(string idUbigeo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUbigeoChannel : CapaAccesoServicios.ProxyUbigeo.IServicioUbigeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUbigeoClient : System.ServiceModel.ClientBase<CapaAccesoServicios.ProxyUbigeo.IServicioUbigeo>, CapaAccesoServicios.ProxyUbigeo.IServicioUbigeo {
        
        public ServicioUbigeoClient() {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE> ListarDepartamentos() {
            return base.Channel.ListarDepartamentos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE>> ListarDepartamentosAsync() {
            return base.Channel.ListarDepartamentosAsync();
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE> ListarProvinciasDepartamento(string idDepartamento) {
            return base.Channel.ListarProvinciasDepartamento(idDepartamento);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE>> ListarProvinciasDepartamentoAsync(string idDepartamento) {
            return base.Channel.ListarProvinciasDepartamentoAsync(idDepartamento);
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE> ListarDistritosProvincia(string idDepartamento, string idProvincia) {
            return base.Channel.ListarDistritosProvincia(idDepartamento, idProvincia);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.UbigeoBE>> ListarDistritosProvinciaAsync(string idDepartamento, string idProvincia) {
            return base.Channel.ListarDistritosProvinciaAsync(idDepartamento, idProvincia);
        }
        
        public CapaAccesoServicios.ProxyUbigeo.UbigeoBE DevuelveUbigeo(string idUbigeo) {
            return base.Channel.DevuelveUbigeo(idUbigeo);
        }
        
        public System.Threading.Tasks.Task<CapaAccesoServicios.ProxyUbigeo.UbigeoBE> DevuelveUbigeoAsync(string idUbigeo) {
            return base.Channel.DevuelveUbigeoAsync(idUbigeo);
        }
    }
}
