//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoServicios.ProxyConsumo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsumoBE", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class ConsumoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdConsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdEstadoConsumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdReservaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdConsumo {
            get {
                return this.IdConsumoField;
            }
            set {
                if ((this.IdConsumoField.Equals(value) != true)) {
                    this.IdConsumoField = value;
                    this.RaisePropertyChanged("IdConsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdEstadoConsumo {
            get {
                return this.IdEstadoConsumoField;
            }
            set {
                if ((this.IdEstadoConsumoField.Equals(value) != true)) {
                    this.IdEstadoConsumoField = value;
                    this.RaisePropertyChanged("IdEstadoConsumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdReserva {
            get {
                return this.IdReservaField;
            }
            set {
                if ((this.IdReservaField.Equals(value) != true)) {
                    this.IdReservaField = value;
                    this.RaisePropertyChanged("IdReserva");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsumo.IServicioConsumo")]
    public interface IServicioConsumo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsumo/ListarConsumoReserva", ReplyAction="http://tempuri.org/IServicioConsumo/ListarConsumoReservaResponse")]
        CapaAccesoServicios.ProxyConsumo.ConsumoBE[] ListarConsumoReserva(short IdReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsumo/ListarConsumoReserva", ReplyAction="http://tempuri.org/IServicioConsumo/ListarConsumoReservaResponse")]
        System.Threading.Tasks.Task<CapaAccesoServicios.ProxyConsumo.ConsumoBE[]> ListarConsumoReservaAsync(short IdReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsumo/InsertarConsumoReserva", ReplyAction="http://tempuri.org/IServicioConsumo/InsertarConsumoReservaResponse")]
        bool InsertarConsumoReserva(CapaAccesoServicios.ProxyConsumo.ConsumoBE objConsumoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsumo/InsertarConsumoReserva", ReplyAction="http://tempuri.org/IServicioConsumo/InsertarConsumoReservaResponse")]
        System.Threading.Tasks.Task<bool> InsertarConsumoReservaAsync(CapaAccesoServicios.ProxyConsumo.ConsumoBE objConsumoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsumo/ActualizarConsumoReserva", ReplyAction="http://tempuri.org/IServicioConsumo/ActualizarConsumoReservaResponse")]
        bool ActualizarConsumoReserva(CapaAccesoServicios.ProxyConsumo.ConsumoBE objConsumoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsumo/ActualizarConsumoReserva", ReplyAction="http://tempuri.org/IServicioConsumo/ActualizarConsumoReservaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarConsumoReservaAsync(CapaAccesoServicios.ProxyConsumo.ConsumoBE objConsumoBE);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsumoChannel : CapaAccesoServicios.ProxyConsumo.IServicioConsumo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsumoClient : System.ServiceModel.ClientBase<CapaAccesoServicios.ProxyConsumo.IServicioConsumo>, CapaAccesoServicios.ProxyConsumo.IServicioConsumo {
        
        public ServicioConsumoClient() {
        }
        
        public ServicioConsumoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsumoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsumoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsumoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaAccesoServicios.ProxyConsumo.ConsumoBE[] ListarConsumoReserva(short IdReserva) {
            return base.Channel.ListarConsumoReserva(IdReserva);
        }
        
        public System.Threading.Tasks.Task<CapaAccesoServicios.ProxyConsumo.ConsumoBE[]> ListarConsumoReservaAsync(short IdReserva) {
            return base.Channel.ListarConsumoReservaAsync(IdReserva);
        }
        
        public bool InsertarConsumoReserva(CapaAccesoServicios.ProxyConsumo.ConsumoBE objConsumoBE) {
            return base.Channel.InsertarConsumoReserva(objConsumoBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarConsumoReservaAsync(CapaAccesoServicios.ProxyConsumo.ConsumoBE objConsumoBE) {
            return base.Channel.InsertarConsumoReservaAsync(objConsumoBE);
        }
        
        public bool ActualizarConsumoReserva(CapaAccesoServicios.ProxyConsumo.ConsumoBE objConsumoBE) {
            return base.Channel.ActualizarConsumoReserva(objConsumoBE);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarConsumoReservaAsync(CapaAccesoServicios.ProxyConsumo.ConsumoBE objConsumoBE) {
            return base.Channel.ActualizarConsumoReservaAsync(objConsumoBE);
        }
    }
}
