//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoServicios.ProxyCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteBE", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class ClienteBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdTipoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoCelularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdTipoCliente {
            get {
                return this.IdTipoClienteField;
            }
            set {
                if ((this.IdTipoClienteField.Equals(value) != true)) {
                    this.IdTipoClienteField = value;
                    this.RaisePropertyChanged("IdTipoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo {
            get {
                return this.IdUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUbigeoField, value) != true)) {
                    this.IdUbigeoField = value;
                    this.RaisePropertyChanged("IdUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoCasa {
            get {
                return this.TelefonoCasaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoCasaField, value) != true)) {
                    this.TelefonoCasaField = value;
                    this.RaisePropertyChanged("TelefonoCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefonoCelular {
            get {
                return this.TelefonoCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoCelularField, value) != true)) {
                    this.TelefonoCelularField = value;
                    this.RaisePropertyChanged("TelefonoCelular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/DevuelveClientePorDNI", ReplyAction="http://tempuri.org/IServicioCliente/DevuelveClientePorDNIResponse")]
        CapaAccesoServicios.ProxyCliente.ClienteBE DevuelveClientePorDNI(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/DevuelveClientePorDNI", ReplyAction="http://tempuri.org/IServicioCliente/DevuelveClientePorDNIResponse")]
        System.Threading.Tasks.Task<CapaAccesoServicios.ProxyCliente.ClienteBE> DevuelveClientePorDNIAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        bool InsertarCliente(CapaAccesoServicios.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarClienteAsync(CapaAccesoServicios.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(CapaAccesoServicios.ProxyCliente.ClienteBE objClienteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(CapaAccesoServicios.ProxyCliente.ClienteBE objClienteBE);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioClienteChannel : CapaAccesoServicios.ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<CapaAccesoServicios.ProxyCliente.IServicioCliente>, CapaAccesoServicios.ProxyCliente.IServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaAccesoServicios.ProxyCliente.ClienteBE DevuelveClientePorDNI(string dni) {
            return base.Channel.DevuelveClientePorDNI(dni);
        }
        
        public System.Threading.Tasks.Task<CapaAccesoServicios.ProxyCliente.ClienteBE> DevuelveClientePorDNIAsync(string dni) {
            return base.Channel.DevuelveClientePorDNIAsync(dni);
        }
        
        public bool InsertarCliente(CapaAccesoServicios.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.InsertarCliente(objClienteBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClienteAsync(CapaAccesoServicios.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.InsertarClienteAsync(objClienteBE);
        }
        
        public bool ActualizarCliente(CapaAccesoServicios.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.ActualizarCliente(objClienteBE);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(CapaAccesoServicios.ProxyCliente.ClienteBE objClienteBE) {
            return base.Channel.ActualizarClienteAsync(objClienteBE);
        }
    }
}
