//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int id_Cliente { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Nombres { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string NroDocumento { get; set; }
        public string Correo { get; set; }
        public string Telefono_Casa { get; set; }
        public string Telefono_Celular { get; set; }
        public string Direccion { get; set; }
        public string id_Ubigeo { get; set; }
        public Nullable<byte> id_Tipo_Cliente { get; set; }
    
        public virtual Ubigeo Ubigeo { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
