//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento_Detalle
    {
        public string id_Serie { get; set; }
        public string id_Correlativo { get; set; }
        public byte Nro_Item { get; set; }
        public short id_Producto { get; set; }
        public decimal Valor_Venta { get; set; }
        public decimal Igv { get; set; }
        public decimal Sub_Total { get; set; }
    
        public virtual Documento Documento { get; set; }
    }
}
