//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento_Detalle
    {
        public string id_Serie { get; set; }
        public string id_Correlativo { get; set; }
        public byte Nro_Item { get; set; }
        public short id_Producto { get; set; }
        public decimal Valor_Venta { get; set; }
        public decimal Igv { get; set; }
        public decimal Sub_Total { get; set; }
    
        public virtual Documento Documento { get; set; }
    }
}
