//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.Documento_Detalle = new HashSet<Documento_Detalle>();
        }
    
        public string id_Serie { get; set; }
        public string id_Correlativo { get; set; }
        public short id_Reserva { get; set; }
        public byte id_Estado_Documento { get; set; }
        public byte id_Tipo_Documento { get; set; }
        public decimal Valor_Venta_Total { get; set; }
        public decimal Valor_Igv_Total { get; set; }
        public decimal Importe_Total { get; set; }
    
        public virtual Reserva Reserva { get; set; }
        public virtual ICollection<Documento_Detalle> Documento_Detalle { get; set; }
    }
}
