//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public Habitacion()
        {
            this.Precio_Especial = new HashSet<Precio_Especial>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public short id_Habitacion { get; set; }
        public byte id_Sede { get; set; }
        public byte id_Estado_Habitacion { get; set; }
        public Nullable<byte> id_Tipo_Habitacion { get; set; }
        public Nullable<byte> Piso { get; set; }
        public decimal Precio { get; set; }
        public Nullable<bool> flag_Fecha_Especial { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Sede Sede { get; set; }
        public virtual ICollection<Precio_Especial> Precio_Especial { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
