//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class hotelproEntities1 : DbContext
    {
        public hotelproEntities1()
            : base("name=hotelproEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Consumo> Consumo { get; set; }
        public DbSet<Documento> Documento { get; set; }
        public DbSet<Documento_Detalle> Documento_Detalle { get; set; }
        public DbSet<Habitacion> Habitacion { get; set; }
        public DbSet<Precio_Especial> Precio_Especial { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Reserva> Reserva { get; set; }
        public DbSet<Sede> Sede { get; set; }
        public DbSet<Ubigeo> Ubigeo { get; set; }
    
        public virtual ObjectResult<USP_Listar_Frecuencia_Cliente_Result> USP_Listar_Frecuencia_Cliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Frecuencia_Cliente_Result>("USP_Listar_Frecuencia_Cliente");
        }
    
        public virtual ObjectResult<USP_Listar_Frecuencia_Cliente_Result> ListarFrecuenciaCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Frecuencia_Cliente_Result>("ListarFrecuenciaCliente");
        }
    
        public virtual ObjectResult<USP_Listar_Frecuencia_Cliente_Result> USP_Listar_Frecuencia_Cliente1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Frecuencia_Cliente_Result>("USP_Listar_Frecuencia_Cliente1");
        }
    
        public virtual ObjectResult<USP_Listar_Reserva_Por_Fecha_Estado_Result> USP_Listar_Reserva_Por_Fecha_Estado(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fin, Nullable<int> id_Estado)
        {
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("inicio", inicio) :
                new ObjectParameter("inicio", typeof(System.DateTime));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("fin", fin) :
                new ObjectParameter("fin", typeof(System.DateTime));
    
            var id_EstadoParameter = id_Estado.HasValue ?
                new ObjectParameter("id_Estado", id_Estado) :
                new ObjectParameter("id_Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Reserva_Por_Fecha_Estado_Result>("USP_Listar_Reserva_Por_Fecha_Estado", inicioParameter, finParameter, id_EstadoParameter);
        }
    
        public virtual ObjectResult<USP_Listar_Reserva_Por_Fecha_Estado_Result> ListarReservaPorFechaEstado(Nullable<System.DateTime> inicio, Nullable<System.DateTime> fin, Nullable<int> id_Estado)
        {
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("inicio", inicio) :
                new ObjectParameter("inicio", typeof(System.DateTime));
    
            var finParameter = fin.HasValue ?
                new ObjectParameter("fin", fin) :
                new ObjectParameter("fin", typeof(System.DateTime));
    
            var id_EstadoParameter = id_Estado.HasValue ?
                new ObjectParameter("id_Estado", id_Estado) :
                new ObjectParameter("id_Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Reserva_Por_Fecha_Estado_Result>("ListarReservaPorFechaEstado", inicioParameter, finParameter, id_EstadoParameter);
        }
    }
}
