//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class hotelproEntities : DbContext
    {
        public hotelproEntities()
            : base("name=hotelproEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Consumo> Consumo { get; set; }
        public DbSet<Documento> Documento { get; set; }
        public DbSet<Documento_Detalle> Documento_Detalle { get; set; }
        public DbSet<Habitacion> Habitacion { get; set; }
        public DbSet<Precio_Especial> Precio_Especial { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Reserva> Reserva { get; set; }
        public DbSet<Sede> Sede { get; set; }
        public DbSet<Ubigeo> Ubigeo { get; set; }
    
        public virtual ObjectResult<USP_Listar_Habitaciones_Por_Fecha_Result> USP_Listar_Habitaciones_Por_Fecha(Nullable<byte> id_Sede, Nullable<System.DateTime> fecha_Inicio_Reserva, Nullable<System.DateTime> fecha_Fin_Reserva, Nullable<byte> id_Tipo_Habitacion)
        {
            var id_SedeParameter = id_Sede.HasValue ?
                new ObjectParameter("id_Sede", id_Sede) :
                new ObjectParameter("id_Sede", typeof(byte));
    
            var fecha_Inicio_ReservaParameter = fecha_Inicio_Reserva.HasValue ?
                new ObjectParameter("fecha_Inicio_Reserva", fecha_Inicio_Reserva) :
                new ObjectParameter("fecha_Inicio_Reserva", typeof(System.DateTime));
    
            var fecha_Fin_ReservaParameter = fecha_Fin_Reserva.HasValue ?
                new ObjectParameter("fecha_Fin_Reserva", fecha_Fin_Reserva) :
                new ObjectParameter("fecha_Fin_Reserva", typeof(System.DateTime));
    
            var id_Tipo_HabitacionParameter = id_Tipo_Habitacion.HasValue ?
                new ObjectParameter("id_Tipo_Habitacion", id_Tipo_Habitacion) :
                new ObjectParameter("id_Tipo_Habitacion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Habitaciones_Por_Fecha_Result>("USP_Listar_Habitaciones_Por_Fecha", id_SedeParameter, fecha_Inicio_ReservaParameter, fecha_Fin_ReservaParameter, id_Tipo_HabitacionParameter);
        }
    
        public virtual ObjectResult<USP_Listar_Habitaciones_Por_Fecha_Tipo_Result> USP_Listar_Habitaciones_Por_Fecha_Tipo(Nullable<byte> id_Sede, Nullable<System.DateTime> fecha_Inicio_Reserva, Nullable<System.DateTime> fecha_Fin_Reserva, Nullable<byte> id_Tipo_Habitacion)
        {
            var id_SedeParameter = id_Sede.HasValue ?
                new ObjectParameter("id_Sede", id_Sede) :
                new ObjectParameter("id_Sede", typeof(byte));
    
            var fecha_Inicio_ReservaParameter = fecha_Inicio_Reserva.HasValue ?
                new ObjectParameter("fecha_Inicio_Reserva", fecha_Inicio_Reserva) :
                new ObjectParameter("fecha_Inicio_Reserva", typeof(System.DateTime));
    
            var fecha_Fin_ReservaParameter = fecha_Fin_Reserva.HasValue ?
                new ObjectParameter("fecha_Fin_Reserva", fecha_Fin_Reserva) :
                new ObjectParameter("fecha_Fin_Reserva", typeof(System.DateTime));
    
            var id_Tipo_HabitacionParameter = id_Tipo_Habitacion.HasValue ?
                new ObjectParameter("id_Tipo_Habitacion", id_Tipo_Habitacion) :
                new ObjectParameter("id_Tipo_Habitacion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Habitaciones_Por_Fecha_Tipo_Result>("USP_Listar_Habitaciones_Por_Fecha_Tipo", id_SedeParameter, fecha_Inicio_ReservaParameter, fecha_Fin_ReservaParameter, id_Tipo_HabitacionParameter);
        }
    
        public virtual ObjectResult<USP_Listar_Habitaciones_Libres_Result> USP_Listar_Habitaciones_Libres(Nullable<byte> id_Sede, Nullable<System.DateTime> fecha_Inicio_Reserva, Nullable<System.DateTime> fecha_Fin_Reserva, Nullable<byte> id_Tipo_Habitacion)
        {
            var id_SedeParameter = id_Sede.HasValue ?
                new ObjectParameter("id_Sede", id_Sede) :
                new ObjectParameter("id_Sede", typeof(byte));
    
            var fecha_Inicio_ReservaParameter = fecha_Inicio_Reserva.HasValue ?
                new ObjectParameter("fecha_Inicio_Reserva", fecha_Inicio_Reserva) :
                new ObjectParameter("fecha_Inicio_Reserva", typeof(System.DateTime));
    
            var fecha_Fin_ReservaParameter = fecha_Fin_Reserva.HasValue ?
                new ObjectParameter("fecha_Fin_Reserva", fecha_Fin_Reserva) :
                new ObjectParameter("fecha_Fin_Reserva", typeof(System.DateTime));
    
            var id_Tipo_HabitacionParameter = id_Tipo_Habitacion.HasValue ?
                new ObjectParameter("id_Tipo_Habitacion", id_Tipo_Habitacion) :
                new ObjectParameter("id_Tipo_Habitacion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Habitaciones_Libres_Result>("USP_Listar_Habitaciones_Libres", id_SedeParameter, fecha_Inicio_ReservaParameter, fecha_Fin_ReservaParameter, id_Tipo_HabitacionParameter);
        }
    
        public virtual ObjectResult<USP_Listar_Habitaciones_Por_Fecha_Tipo_Result> Listar_Habitaciones_Por_Fecha_Tipo(Nullable<byte> id_Sede, Nullable<System.DateTime> fecha_Inicio_Reserva, Nullable<System.DateTime> fecha_Fin_Reserva, Nullable<byte> id_Tipo_Habitacion)
        {
            var id_SedeParameter = id_Sede.HasValue ?
                new ObjectParameter("id_Sede", id_Sede) :
                new ObjectParameter("id_Sede", typeof(byte));
    
            var fecha_Inicio_ReservaParameter = fecha_Inicio_Reserva.HasValue ?
                new ObjectParameter("fecha_Inicio_Reserva", fecha_Inicio_Reserva) :
                new ObjectParameter("fecha_Inicio_Reserva", typeof(System.DateTime));
    
            var fecha_Fin_ReservaParameter = fecha_Fin_Reserva.HasValue ?
                new ObjectParameter("fecha_Fin_Reserva", fecha_Fin_Reserva) :
                new ObjectParameter("fecha_Fin_Reserva", typeof(System.DateTime));
    
            var id_Tipo_HabitacionParameter = id_Tipo_Habitacion.HasValue ?
                new ObjectParameter("id_Tipo_Habitacion", id_Tipo_Habitacion) :
                new ObjectParameter("id_Tipo_Habitacion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Habitaciones_Por_Fecha_Tipo_Result>("Listar_Habitaciones_Por_Fecha_Tipo", id_SedeParameter, fecha_Inicio_ReservaParameter, fecha_Fin_ReservaParameter, id_Tipo_HabitacionParameter);
        }
    
        public virtual ObjectResult<USP_Listar_Habitaciones_Libres_Result> Listar_Habitaciones_Libres(Nullable<byte> id_Sede, Nullable<System.DateTime> fecha_Inicio_Reserva, Nullable<System.DateTime> fecha_Fin_Reserva, Nullable<byte> id_Tipo_Habitacion)
        {
            var id_SedeParameter = id_Sede.HasValue ?
                new ObjectParameter("id_Sede", id_Sede) :
                new ObjectParameter("id_Sede", typeof(byte));
    
            var fecha_Inicio_ReservaParameter = fecha_Inicio_Reserva.HasValue ?
                new ObjectParameter("fecha_Inicio_Reserva", fecha_Inicio_Reserva) :
                new ObjectParameter("fecha_Inicio_Reserva", typeof(System.DateTime));
    
            var fecha_Fin_ReservaParameter = fecha_Fin_Reserva.HasValue ?
                new ObjectParameter("fecha_Fin_Reserva", fecha_Fin_Reserva) :
                new ObjectParameter("fecha_Fin_Reserva", typeof(System.DateTime));
    
            var id_Tipo_HabitacionParameter = id_Tipo_Habitacion.HasValue ?
                new ObjectParameter("id_Tipo_Habitacion", id_Tipo_Habitacion) :
                new ObjectParameter("id_Tipo_Habitacion", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Habitaciones_Libres_Result>("Listar_Habitaciones_Libres", id_SedeParameter, fecha_Inicio_ReservaParameter, fecha_Fin_ReservaParameter, id_Tipo_HabitacionParameter);
        }
    }
}
