//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelproEntities : DbContext
    {
        public hotelproEntities()
            : base("name=hotelproEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Consumo> Consumo { get; set; }
        public DbSet<Documento> Documento { get; set; }
        public DbSet<Documento_Detalle> Documento_Detalle { get; set; }
        public DbSet<Habitacion> Habitacion { get; set; }
        public DbSet<Precio_Especial> Precio_Especial { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Reserva> Reserva { get; set; }
        public DbSet<Sede> Sede { get; set; }
        public DbSet<Ubigeo> Ubigeo { get; set; }
    }
}
