//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Consumo = new HashSet<Consumo>();
        }
    
        public short id_Producto { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
    
        public virtual ICollection<Consumo> Consumo { get; set; }
    }
}
