//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Consumo = new HashSet<Consumo>();
        }
    
        public short id_Producto { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
    
        public virtual ICollection<Consumo> Consumo { get; set; }
    }
}
