//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public Reserva()
        {
            this.Documento = new HashSet<Documento>();
        }
    
        public short id_Reserva { get; set; }
        public int id_Cliente { get; set; }
        public short id_Habitacion { get; set; }
        public byte id_Estado_Reserva { get; set; }
        public Nullable<short> id_Consumo { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public System.DateTime Fecha_Salida { get; set; }
        public System.DateTime Fecha_Inicio_Reserva { get; set; }
        public System.DateTime Fecha_Fin_Reserva { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Consumo Consumo { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
