//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.Documento_Detalle = new HashSet<Documento_Detalle>();
        }
    
        public string id_Serie { get; set; }
        public string id_Correlativo { get; set; }
        public short id_Reserva { get; set; }
        public byte id_Estado_Documento { get; set; }
        public byte id_Tipo_Documento { get; set; }
        public decimal Valor_Venta_Total { get; set; }
        public decimal Valor_Igv_Total { get; set; }
        public decimal Importe_Total { get; set; }
    
        public virtual ICollection<Documento_Detalle> Documento_Detalle { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
