//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubigeo
    {
        public Ubigeo()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Sede = new HashSet<Sede>();
        }
    
        public string id_Ubigeo { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public string idContinente { get; set; }
        public string idPais { get; set; }
        public string idDepartamento { get; set; }
        public string idProvincia { get; set; }
        public string idDistrito { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Sede> Sede { get; set; }
    }
}
